name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 05 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: Fabri-dev
      - name: Commit & Push
        run: |
           git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add output/3d-contrib-graph.svg
          git commit -m "generated"
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository_owner }}/${{ github.repository }}.git HEAD:main

          
